### ISSUE TITLE
Netlify Deployment failed

### ISSUE THREAD

**Issue by futuresoup** [tmns/11ty-feedback#1]
Aw I was so excited about this, but my deployment failed with the default Netlify setup :`( 

I'm not a dev unfortunately...any ideas?

[Here is the log output.](https://paste.sh/lM9FAVMH#NGAa2VGlZKksZ4g8BDsGOLNu)

Please help? Thank you <3

**Comment by tmns** [comment]
Hey there @futuresoup, thanks for reporting!

I tried updating some of the project's dependencies. Can you give it another try when you get a chance?

Note that if you deployed it from a local copy of the code on your computer, you'll need to run `git pull` to bring in the latest changes.

**Comment by futuresoup** [comment]
@tmns thanks for your response.

I can guarantee it wasn't a local copy because I'm still struggling to get npm to work on my machine :p 

That being said - I just got a successful deploy using your docs!

Your Readme link worked: [try deploying it to your own Netlify instance now](https://app.netlify.com/start/deploy?repository=https://github.com/tmns/11ty-feedback)

Now time for some feedback, in the spirit of your project! :)

The reason why I like your project so much is because I had the exact same idea but didn't know how to do it outside of a Google Form.

One thing I would consider,

Why not offer a trade?

Since people are taking the time to give you valuable feedback,

You could offer the same value in return. 

You'll be more likely to earn participants and everybody wins and gets to improve! :D

**Comment by tmns** [comment]
Glad it worked!

And that's a good consideration! This template was created more for use in teams however, where teammates would deploy their own versions and send them to each other when wanting feedback. So there wasn't really a notion of "earning participants".

But the beauty of open source is that now you have [your own copy of this on GitHub](https://github.com/futuresoup/11ty-feedback-2nd-try)! So you can edit your version's files and include any message you want 🙌
