### ISSUE TITLE
How do you configure the form?

### ISSUE THREAD

**Issue by futuresoup** [tmns/11ty-feedback#2]
Can you kindly update the docs to explain how to set up the form to work?

Or respond here?

I deployed to Netlify and filled out a test form.

The submission worked, but I have no idea where it sent to :)

Thanks!

**Comment by tmns** [comment]
Hey there, form submissions are handled by Netlify. 

For me, if I log in to my Netlify account and click on the site for this project, near the bottom of the "overview" page there is a section called "Recent form submissions". You can check there and also refer to and can be changed at any time by them, so I would refer to [their docs](https://docs.netlify.com/forms/submissions/). 

If I'm not mistaken, there should also be a way for you to configure the form submissions to be forwarded to your email as well. Again though, you should check Netlify's docs for that.

**Comment by futuresoup** [comment]
That is really great they handle that, thanks!!
